import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import { env } from "@/env";
import type { paths } from "../types/zenmo-schema"; // generated by openapi-typescript

const fetchClient = createFetchClient<paths>({
  baseUrl: env.NEXT_PUBLIC_BACKEND_URL,
});

export const $api = createClient(fetchClient);
