import createFetchClient from "openapi-fetch";
import createClient from "openapi-react-query";
import type { paths } from "../types/zenmo-schema"; // generated by openapi-typescript
import { env } from "@/env";

const fetchClient = createFetchClient<paths>({
  baseUrl: env.BACKEND_URL || env.NEXT_PUBLIC_BACKEND_URL,
});

export const $api = createClient(fetchClient);